In [45]:
import numpy as np
np.__version__

'1.15.1'

# 1D Array Indexing & Slicing

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a[2:5]

array([2, 3, 4])

In [28]:
a[::2]
# a[0: len(a): 2]

array([0, 2, 4])

In [34]:
# Reverse Numpy Array
a[::-1]

array([4, 3, 2, 1, 0])

# 2D Array Indexing & Slicing

![](https://miro.medium.com/max/295/1*lExJVZqZVEXEW0oZWCwGVA.png)

In [78]:
c = np.arange(20).reshape(4, 5)

In [77]:
# To access elements
c[2, 2]

12

In [80]:
c[2:, 1:3]

array([[11, 12],
       [16, 17]])

![](http://i.imgur.com/kT2yg7h.png)

In [82]:
d = np.arange(25).reshape(5, 5)

In [84]:
# Purple Cells
d[:, 1]

array([ 1,  6, 11, 16, 21])

In [87]:
# Yellow Cells
d[::2, 2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [89]:
# Red Cells
d[1, 2:4]

array([7, 8])

In [91]:
# Green Cells
d[3:, 3:]

array([[18, 19],
       [23, 24]])

# Fancy Indexing With Arrays Of Integers

In [92]:
a = np.arange(5) ** 2
a

array([ 0,  1,  4,  9, 16])

In [93]:
i = np.array([3, 1, 3, 0])
i

array([3, 1, 3, 0])

In [94]:
a[i]

array([9, 1, 9, 0])

In [95]:
j = np.array([[0,3], [2, 1]])
j

array([[0, 3],
       [2, 1]])

In [96]:
a[j]

array([[0, 9],
       [4, 1]])

In [ ]:
f